### PR TITLE
add gesis_download fxn to streamline usage

### PR DESCRIPTION
**Pull request by fsolt**
I've added a new fxn, `gesis_download`, that mimics the streamlined approach I used for `pewdata`: it rolls setup, login, and download into a one-liner.  I also added a new vignette to describe how to use it that pulls some material from the original vignette.

### CODE REVIEW

**Comment by fsolt** [comment]
Any thoughts on this, Eric?

**Comment by expersso** [comment]
Thanks for this, Frederick. My apologies for not getting to this sooner. I was
taking a look at it this weekend, but embarrassingly I can't seem to get my own
package working at the moment! 

It seems like the latest versions of Firefox and Selenium are out of sync, and 
as a result I can't get RSelenium (let alone gesis) to work. This is a common 
and long-standing problem with Selenium, and could almost certainly be solved by
simply downgrading Firefox back to an earlier version, but I haven't gotten
around to verifying that yet.

As for the PR, I'm not sure I'm entirely convinced that rolling everything up
into one function is advisable here. Let me try to explain my reasoning.

First, it doesn't separate concerns very well. `gesis_download` would now:
1. make a Firefox profile
2. check for a server
3. start a server
4. log in
5. iterate over DOIs
6. interact with the filesystem
7. close the server

All of those things have quite substantial side-effects and, as such, can go wrong in countless
ways. By rolling them up into one function we would make debugging much more
difficult, since e.g. one malformed file or page would blow up the entire function and output
a very opaque error message.

Second, it doesn't make the package very amenable to many functional programming 
patterns, which rely on small functions that can easily be composed 
together. For example, I might want to output a message saying how many files 
I've downloaded (and not just which DOI), which I could easily do with a
closure, e.g.:

```
w_msg <- function(f) { 
  force(f)
  i <- i + 1 
  function(...) {
    message("Downloading file number: ", i)
    i <<- i + 1
    f(...)
  }
}

lapply(doi, w_msg(download_dataset), remDr = gesis_remDr)
```

To do something similar with `gesis_download` I would need to go in and change
the source code directly. The same reasoning would apply for e.g. custom 
error handlers, outputting messages of the size of files being downloaded, etc.

Finally, if the end-user wants to wrap everything up into one function, it would
be straightforward for him or her to just put all the logic in a simple wrapper:

```
download_dois <- function(dois) {
  gesis_remDr <- setup_gesis(download_dir = "downloads")
  login_gesis(gesis_remDr, user = "myusername", pass = "mypassword")

  on.exit(gesis_remDr$Close())
  on.exit(gesis_remDr$closeServer(), TRUE)

  lapply(dois, download_dataset, remDr = gesis_remDr)
}
```

This way we also don't need to worry about adding numerous function arguments to
try to second guess which parameters the user might want to control 
himself/herself.

**Comment by fsolt** [comment]
I completely agree that it isn't a solution to all use cases; I see `download_gesis` as a complement, not a substitute, for your existing functions.  Here are what I think are its advantages:
1. provides a clean, streamlined approach to the most common use case,
2. automatically downloads codebooks when available, and
3. automatically deals with the "stray" zip files.

Again, all this automation and streamlining is obviously not going to be for everyone, but there's a lot of people who need to be dragged kicking and screaming to a reproducible workflow, and I see this as a way to make it as easy for them as possible.  

If you prefer, I'll wrap it up into its own package.  I really rather not, though, because the last thing CRAN needs is another duplicative package.

**Comment by expersso** [comment]
Since I refactored the entire package to avoid the use of Selenium, I'll close this. I'm still thinking about a way to avoid the two-step process of login/download, which I think should be possible with cookie maintenance in `rvest` without using `html_session`. So I've left that issue open for now. 

Happy to receive feedback on the new structure.

**Pull request closed without merging**
